#!/usr/bin/env sh

set -eux

CMD_ARGS="-p" "$MINI_HTTPD_PORT" "-d" "$MINI_HTTPD_DIR"

if [ -n "$MINI_HTTPD_CONFIG" ]; then
    CMD_ARGS="$CMD_ARGS" "-C" "$MINI_HTTPD_CONFIG"
else
    [ -n "$MINI_HTTPD_DATADIR" ]  && CMD_ARGS="$CMD_ARGS" "-dd" "$MINI_HTTPD_DATADIR"
    [ -n "$MINI_HTTPD_CGIPAT" ]   && CMD_ARGS="$CMD_ARGS" "-c" "$MINI_HTTPD_CGIPAT"
    [ -n "$MINI_HTTPD_USER" ]     && CMD_ARGS="$CMD_ARGS" "-u" "$MINI_HTTPD_USER"
    [ -n "$MINI_HTTPD_HOST" ]     && CMD_ARGS="$CMD_ARGS" "-h" "$MINI_HTTPD_HOST"
    [ -n "$MINI_HTTPD_CHROOT" ]   && CMD_ARGS="$CMD_ARGS" "-r"
    [ -n "$MINI_HTTPD_VHOST" ]    && CMD_ARGS="$CMD_ARGS" "-v" "$MINI_HTTPD_VHOST"
    [ -n "$MINI_HTTPD_LOGFILE" ]  && CMD_ARGS="$CMD_ARGS" "-l" "$MINI_HTTPD_LOGFILE"
    [ -n "$MINI_HTTPD_PIDFILE" ]  && CMD_ARGS="$CMD_ARGS" "-i" "$MINI_HTTPD_PIDFILE"
    [ -n "$MINI_HTTPD_CHARSET" ]  && CMD_ARGS="$CMD_ARGS" "-T" "$MINI_HTTPD_CHARSET"
    [ -n "$MINI_HTTPD_P3P" ]      && CMD_ARGS="$CMD_ARGS" "-P" "$MINI_HTTPD_P3P"
    [ -n "$MINI_HTTPD_MAXAGE" ]   && CMD_ARGS="$CMD_ARGS" "-M" "$MINI_HTTPD_MAXAGE"
    [ -n "$MINI_HTTPD_SSL" ]      && CMD_ARGS="$CMD_ARGS" "-S"
    [ -n "$MINI_HTTPD_CERTFILE" ] && CMD_ARGS="$CMD_ARGS" "-E" "$MINI_HTTPD_CERTFILE"
    [ -n "$MINI_HTTPD_CIPHER" ]   && CMD_ARGS="$CMD_ARGS" "-Y" "$MINI_HTTPD_CIPHER"
fi

exec "/usr/sbin/mini_httpd -D $CMD_ARGS"