collections:
  - name: amazon.aws
    version: "*"
  - name: ansible.netcommon
    version: "*"
  - name: ansible.posix
    version: "*"
  - name: ansible.utils
    version: "*"
  - name: ansible.windows
    version: "*"
  - name: arista.eos
    version: "*"
  - name: awx.awx
    version: "*"
  - name: azure.azcollection
    version: "*"
  - name: check_point.mgmt
    version: "*"
  - name: chocolatey.chocolatey
    version: "*"
  - name: cisco.aci
    version: "*"
  - name: cisco.asa
    version: "*"
  - name: cisco.dnac
    version: "*"
  - name: cisco.intersight
    version: "*"
  - name: cisco.ios
    version: "*"
  - name: cisco.iosxr
    version: "*"
  - name: cisco.ise
    version: "*"
  - name: cisco.meraki
    version: "*"
  - name: cisco.mso
    version: "*"
  - name: cisco.nxos
    version: "*"
  - name: cisco.ucs
    version: "*"
  - name: cloud.common
    version: "*"
  - name: cloudscale_ch.cloud
    version: "*"
  - name: community.aws
    version: "*"
  - name: community.ciscosmb
    version: "*"
  - name: community.crypto
    version: "*"
  - name: community.digitalocean
    version: "*"
  - name: community.dns
    version: "*"
  - name: community.docker
    version: "*"
  - name: community.general
    version: "*"
  - name: community.grafana
    version: "*"
  - name: community.hashi_vault
    version: "*"
  - name: community.hrobot
    version: "*"
  - name: community.library_inventory_filtering_v1
    version: "*"
  - name: community.libvirt
    version: "*"
  - name: community.mongodb
    version: "*"
  - name: community.mysql
    version: "*"
  - name: community.network
    version: "*"
  - name: community.okd
    version: "*"
  - name: community.postgresql
    version: "*"
  - name: community.proxysql
    version: "*"
  - name: community.rabbitmq
    version: "*"
  - name: community.routeros
    version: "*"
  - name: community.sap_libs
    version: "*"
  - name: community.sops
    version: "*"
  - name: community.vmware
    version: "*"
  - name: community.windows
    version: "*"
  - name: community.zabbix
    version: "*"
  - name: containers.podman
    version: "*"
  - name: cyberark.conjur
    version: "*"
  - name: cyberark.pas
    version: "*"
  - name: dellemc.enterprise_sonic
    version: "*"
  - name: dellemc.openmanage
    version: "*"
  - name: dellemc.powerflex
    version: "*"
  - name: dellemc.unity
    version: "*"
  - name: f5networks.f5_modules
    version: "*"
  - name: fortinet.fortimanager
    version: "*"
  - name: fortinet.fortios
    version: "*"
  - name: google.cloud
    version: "*"
  - name: grafana.grafana
    version: "*"
  - name: hetzner.hcloud
    version: "*"
  - name: ibm.qradar
    version: "*"
  - name: ibm.spectrum_virtualize
    version: "*"
  - name: ibm.storage_virtualize
    version: "*"
  - name: ieisystem.inmanage
    version: "*"
  - name: infinidat.infinibox
    version: "*"
  - name: infoblox.nios_modules
    version: "*"
  - name: inspur.ispim
    version: "*"
  - name: junipernetworks.junos
    version: "*"
  - name: kaytus.ksmanage
    version: "*"
  - name: kubernetes.core
    version: "*"
  - name: kubevirt.core
    version: "*"
  - name: lowlydba.sqlserver
    version: "*"
  - name: microsoft.ad
    version: "*"
  - name: netapp.cloudmanager
    version: "*"
  - name: netapp.ontap
    version: "*"
  - name: netapp.storagegrid
    version: "*"
  - name: netapp_eseries.santricity
    version: "*"
  - name: netbox.netbox
    version: "*"
  - name: ngine_io.cloudstack
    version: "*"
  - name: openstack.cloud
    version: "*"
  - name: ovirt.ovirt
    version: "*"
  - name: purestorage.flasharray
    version: "*"
  - name: purestorage.flashblade
    version: "*"
  - name: sensu.sensu_go
    version: "*"
  - name: splunk.es
    version: "*"
  - name: telekom_mms.icinga_director
    version: "*"
  - name: theforeman.foreman
    version: "*"
  - name: vmware.vmware
    version: "*"
  - name: vmware.vmware_rest
    version: "*"
  - name: vultr.cloud
    version: "*"
  - name: vyos.vyos
    version: "*"
  - name: wti.remote
    version: "*"
  - name: inspur.sm
    version: "*"
  - name: kpfleming.powerdns_auth
    version: "*"